var searchData=
[
  ['init_5fbinding',['init_binding',['../structcereal_1_1detail_1_1init__binding.html',1,'cereal::detail']]],
  ['inputarchive',['InputArchive',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchive_3c_20binaryinputarchive_2c_20allowemptyclasselision_20_3e',['InputArchive&lt; BinaryInputArchive, AllowEmptyClassElision &gt;',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchive_3c_20extendablebinaryinputarchive_2c_20flags_3a_3aforwardsupport_20_3e',['InputArchive&lt; ExtendableBinaryInputArchive, Flags::ForwardSupport &gt;',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchive_3c_20jsoninputarchive_20_3e',['InputArchive&lt; JSONInputArchive &gt;',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchive_3c_20portablebinaryinputarchive_2c_20allowemptyclasselision_20_3e',['InputArchive&lt; PortableBinaryInputArchive, AllowEmptyClassElision &gt;',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchive_3c_20xmlinputarchive_20_3e',['InputArchive&lt; XMLInputArchive &gt;',['../classcereal_1_1InputArchive.html',1,'cereal']]],
  ['inputarchivebase',['InputArchiveBase',['../classcereal_1_1detail_1_1InputArchiveBase.html',1,'cereal::detail']]],
  ['inputbindingcreator',['InputBindingCreator',['../structcereal_1_1detail_1_1InputBindingCreator.html',1,'cereal::detail']]],
  ['inputbindingmap',['InputBindingMap',['../structcereal_1_1detail_1_1InputBindingMap.html',1,'cereal::detail']]],
  ['instantiate_5ffunction',['instantiate_function',['../structcereal_1_1detail_1_1instantiate__function.html',1,'cereal::detail']]],
  ['is_5fdefault_5fconstructible',['is_default_constructible',['../structcereal_1_1traits_1_1is__default__constructible.html',1,'cereal::traits']]],
  ['is_5fenum',['is_enum',['../classcereal_1_1common__detail_1_1is__enum.html',1,'cereal::common_detail']]],
  ['is_5fextendablebinary_5fempty_5fprologue_5fand_5fepilogue1',['is_extendablebinary_empty_prologue_and_epilogue1',['../structcereal_1_1is__extendablebinary__empty__prologue__and__epilogue1.html',1,'cereal']]],
  ['is_5fextendablebinary_5fempty_5fprologue_5fand_5fepilogue1_3c_20binarydata_3c_20t_20_3e_20_3e',['is_extendablebinary_empty_prologue_and_epilogue1&lt; BinaryData&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__empty__prologue__and__epilogue1_3_01BinaryData_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5fempty_5fprologue_5fand_5fepilogue1_3c_20sizetag_3c_20t_20_3e_20_3e',['is_extendablebinary_empty_prologue_and_epilogue1&lt; SizeTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__empty__prologue__and__epilogue1_3_01SizeTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1',['is_extendablebinary_internal_prologue_and_epilogue1',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20detail_3a_3aobjectidtag_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; detail::ObjectIdTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01detail_1_1ObjectIdTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20detail_3a_3apointervaliditytag_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; detail::PointerValidityTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01detail_1_1PointerValidityTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20detail_3a_3apolymorphicidtag_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; detail::PolymorphicIdTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01detail_1_1PolymorphicIdTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20detail_3a_3apolymorphickeytag_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; detail::PolymorphicKeyTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01detail_1_1PolymorphicKeyTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20detail_3a_3aversionidtag_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; detail::VersionIdTag&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01detail_1_1VersionIdTag_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20memory_5fdetail_3a_3aptrwrapper_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; memory_detail::PtrWrapper&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01memory__detail_1_1PtrWrapper_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20namevaluepair_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; NameValuePair&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01NameValuePair_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20std_3a_3aarray_3c_20t_2c_20v_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; std::array&lt; T, V &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01std_1_1array_3_01T_00_01V_01_4_01_4.html',1,'cereal']]],
  ['is_5fextendablebinary_5finternal_5fprologue_5fand_5fepilogue1_3c_20std_3a_3aweak_5fptr_3c_20t_20_3e_20_3e',['is_extendablebinary_internal_prologue_and_epilogue1&lt; std::weak_ptr&lt; T &gt; &gt;',['../structcereal_1_1is__extendablebinary__internal__prologue__and__epilogue1_3_01std_1_1weak__ptr_3_01T_01_4_01_4.html',1,'cereal']]],
  ['is_5finput_5fserializable',['is_input_serializable',['../structcereal_1_1traits_1_1is__input__serializable.html',1,'cereal::traits']]],
  ['is_5fminimal_5ftype',['is_minimal_type',['../structcereal_1_1traits_1_1is__minimal__type.html',1,'cereal::traits']]],
  ['is_5foutput_5fserializable',['is_output_serializable',['../structcereal_1_1traits_1_1is__output__serializable.html',1,'cereal::traits']]],
  ['is_5fsame_5farchive',['is_same_archive',['../structcereal_1_1traits_1_1is__same__archive.html',1,'cereal::traits']]],
  ['is_5fspecialized',['is_specialized',['../structcereal_1_1traits_1_1is__specialized.html',1,'cereal::traits']]],
  ['is_5fstring',['is_string',['../structcereal_1_1traits_1_1detail_1_1is__string.html',1,'cereal::traits::detail']]],
  ['is_5fstring_3c_20std_3a_3abasic_5fstring_3c_20chart_2c_20traits_2c_20alloc_20_3e_20_3e',['is_string&lt; std::basic_string&lt; CharT, Traits, Alloc &gt; &gt;',['../structcereal_1_1traits_1_1detail_1_1is__string_3_01std_1_1basic__string_3_01CharT_00_01Traits_00_01Alloc_01_4_01_4.html',1,'cereal::traits::detail']]],
  ['is_5ftext_5farchive',['is_text_archive',['../structcereal_1_1traits_1_1is__text__archive.html',1,'cereal::traits']]]
];
